/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["debugChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/agui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runAgentWithAGUI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/a2a/agents/{agent_code}/.well-known/agent-card.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgentCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/a2a/agents/{agent_code}/message:send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendA2AMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/a2a/agents/{agent_code}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getA2ATask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/a2a/agents/{agent_code}/tasks/{task_id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelA2ATask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/a2a/agents/{agent_code}/callbacks/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveA2ATaskCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRunTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/loops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunLoops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replayRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replayThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loops/{loop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLoop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loops/{loop_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLoopEvaluations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgent"];
        put: operations["updateAgent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkflows"];
        put?: never;
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCapabilities"];
        put?: never;
        post: operations["createCapability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/capabilities/{capability_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCapability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/capabilities/{capability_code}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateCapability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentEndpoints"];
        put?: never;
        post: operations["createAgentEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/endpoints/{endpoint_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateAgentEndpoint"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/endpoints/{endpoint_code}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateAgentEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/endpoints/{endpoint_code}/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["healthCheckAgentEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMCPServers"];
        put?: never;
        post: operations["createMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{server_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMCPServer"];
        put: operations["updateMCPServer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{server_code}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{server_code}/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["healthCheckMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{server_code}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMCPTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/workflows/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkflow"];
        put: operations["updateWorkflow"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/workflows/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_code}/workflows/{version}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put: operations["updateUser"];
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @example OK */
            code: string;
            /** @example success */
            message: string;
            data: unknown;
            /** @example trace_xxx */
            trace_id: string;
        };
        RegisterRequest: {
            username: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        ChatRequest: {
            provider?: string;
            model?: string;
            messages: {
                /** @enum {string} */
                role: "system" | "user" | "assistant" | "developer";
                content: string;
            }[];
        };
        AGUIRunAgentInput: {
            threadId?: string;
            runId?: string;
            parentRunId?: string;
            messages: Record<string, never>[];
            resume?: Record<string, never>[];
        };
        CreateRunRequest: {
            agent_code: string;
            workflow_version?: number;
            thread_id?: string;
            trigger_type?: string;
            input?: unknown;
            provider?: string;
            model?: string;
        };
        AgentRequest: {
            agent_code: string;
            name: string;
            description?: string;
        };
        CapabilityRequest: {
            capability_code: string;
            name: string;
            description?: string;
            /** @enum {string} */
            capability_type: "workflow" | "remote" | "tool" | "custom";
            /** Format: int64 */
            workflow_id?: number;
            version: string;
            input_schema_json?: string;
            output_schema_json?: string;
            config_json?: string;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        EndpointRequest: {
            endpoint_code: string;
            /** @enum {string} */
            protocol?: "a2a";
            /** @enum {string} */
            transport?: "http" | "https";
            /** Format: uri */
            address: string;
            auth_type?: string;
            credential_ref?: string;
            config_json?: string;
        };
        MCPServerRequest: {
            server_code: string;
            name: string;
            description?: string;
            /** @enum {string} */
            transport?: "streamable_http";
            /** Format: uri */
            endpoint: string;
            auth_type?: string;
            credential_ref?: string;
            config_json?: string;
        };
        WorkflowCreateRequest: {
            version: number;
            definition: Record<string, never>;
        };
        WorkflowUpdateRequest: {
            definition: Record<string, never>;
        };
        A2AMessageSendRequest: {
            message: Record<string, never>;
            configuration?: Record<string, never>;
        };
        /** @description A2A StreamResponse wrapper. The runtime accepts terminal Task or terminal statusUpdate events for callbacks; message and artifactUpdate events are not valid callback payloads. */
        A2ATaskCallback: {
            task: components["schemas"]["A2ATask"];
        } | {
            statusUpdate: components["schemas"]["A2ATaskStatusUpdateEvent"];
        };
        AgentCard: {
            name: string;
            description: string;
            /** Format: uri */
            url: string;
            capabilities: Record<string, never>;
            skills?: Record<string, never>[];
        };
        A2ATask: {
            id?: string;
            contextId?: string;
            status?: components["schemas"]["A2ATaskStatus"];
            history?: Record<string, never>[];
            artifacts?: Record<string, never>[];
        };
        A2ATaskStatusUpdateEvent: {
            contextId?: string;
            taskId: string;
            status: components["schemas"]["A2ATaskStatus"];
            metadata?: Record<string, never>;
        };
        A2ATaskStatus: {
            /** @enum {string} */
            state: "submitted" | "working" | "input-required" | "completed" | "canceled" | "failed" | "rejected";
            message?: Record<string, never>;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: {
        /** @description Unified JSON response envelope. */
        Envelope: {
            headers: {
                "X-Trace-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Unified error envelope. */
        Error: {
            headers: {
                "X-Trace-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
    };
    parameters: {
        AgentCode: string;
        TaskID: string;
        HistoryLength: number;
        RunID: string;
        ThreadID: string;
        LoopID: string;
        UserID: number;
        WorkflowVersion: number;
        IdempotencyKey: string;
        A2AAgentCode: string;
        A2ATimestamp: string;
        A2ANonce: string;
        A2ASignature: string;
        A2AContentSHA256: string;
        A2ANotificationToken: string;
        TraceID: string;
        CapabilityCode: string;
        EndpointCode: string;
        ServerCode: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
            400: components["responses"]["Error"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
            401: components["responses"]["Error"];
        };
    };
    debugChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Streaming provider debug response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Error"];
        };
    };
    runAgentWithAGUI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AGUIRunAgentInput"];
            };
        };
        responses: {
            /** @description Official AG-UI event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getAgentCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A2A Agent Card discovery document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCard"];
                };
            };
            /** @description Agent is not published. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendA2AMessage: {
        parameters: {
            query?: never;
            header: {
                "X-GoAI-Agent-Code": components["parameters"]["A2AAgentCode"];
                "X-GoAI-Timestamp": components["parameters"]["A2ATimestamp"];
                "X-GoAI-Nonce": components["parameters"]["A2ANonce"];
                "X-GoAI-Content-SHA256": components["parameters"]["A2AContentSHA256"];
                Authorization: components["parameters"]["A2ASignature"];
            };
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["A2AMessageSendRequest"];
            };
        };
        responses: {
            /** @description Accepted or completed A2A task. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["A2ATask"];
                };
            };
            /** @description Invalid machine identity or replayed request. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    getA2ATask: {
        parameters: {
            query?: {
                historyLength?: components["parameters"]["HistoryLength"];
            };
            header: {
                "X-GoAI-Agent-Code": components["parameters"]["A2AAgentCode"];
                "X-GoAI-Timestamp": components["parameters"]["A2ATimestamp"];
                "X-GoAI-Nonce": components["parameters"]["A2ANonce"];
                "X-GoAI-Content-SHA256": components["parameters"]["A2AContentSHA256"];
                Authorization: components["parameters"]["A2ASignature"];
            };
            path: {
                agent_code: components["parameters"]["AgentCode"];
                task_id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current A2A task snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["A2ATask"];
                };
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelA2ATask: {
        parameters: {
            query?: never;
            header: {
                "X-GoAI-Agent-Code": components["parameters"]["A2AAgentCode"];
                "X-GoAI-Timestamp": components["parameters"]["A2ATimestamp"];
                "X-GoAI-Nonce": components["parameters"]["A2ANonce"];
                "X-GoAI-Content-SHA256": components["parameters"]["A2AContentSHA256"];
                Authorization: components["parameters"]["A2ASignature"];
            };
            path: {
                agent_code: components["parameters"]["AgentCode"];
                task_id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled or already terminal task. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["A2ATask"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    receiveA2ATaskCallback: {
        parameters: {
            query?: never;
            header: {
                "X-GoAI-Agent-Code": components["parameters"]["A2AAgentCode"];
                "X-GoAI-Timestamp": components["parameters"]["A2ATimestamp"];
                "X-GoAI-Nonce": components["parameters"]["A2ANonce"];
                "X-GoAI-Content-SHA256": components["parameters"]["A2AContentSHA256"];
                Authorization: components["parameters"]["A2ASignature"];
                "A2A-Notification-Token": components["parameters"]["A2ANotificationToken"];
                "X-Trace-ID"?: components["parameters"]["TraceID"];
            };
            path: {
                agent_code: components["parameters"]["AgentCode"];
                task_id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["A2ATaskCallback"];
            };
        };
        responses: {
            /** @description Callback accepted and applied idempotently. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        accepted: boolean;
                    };
                };
            };
            400: components["responses"]["Error"];
            /** @description Invalid callback machine identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Existing Run returned for an idempotent request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            202: components["responses"]["Envelope"];
            409: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
            404: components["responses"]["Error"];
        };
    };
    listRunSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
            404: components["responses"]["Error"];
        };
    };
    getRunTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listRunLoops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    replayRun: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
            202: components["responses"]["Envelope"];
        };
    };
    replayThread: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                thread_id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    source_run_id?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
            202: components["responses"]["Envelope"];
        };
    };
    getLoop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loop_id: components["parameters"]["LoopID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listLoopEvaluations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loop_id: components["parameters"]["LoopID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    activateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    deactivateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    createWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
        };
    };
    listCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    createCapability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
        };
    };
    updateCapability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                capability_code: components["parameters"]["CapabilityCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityRequest"];
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    deactivateCapability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                capability_code: components["parameters"]["CapabilityCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listAgentEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    createAgentEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndpointRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
        };
    };
    updateAgentEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                endpoint_code: components["parameters"]["EndpointCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndpointRequest"];
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    deactivateAgentEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                endpoint_code: components["parameters"]["EndpointCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    healthCheckAgentEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                endpoint_code: components["parameters"]["EndpointCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listMCPServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    createMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPServerRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
        };
    };
    getMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_code: components["parameters"]["ServerCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    updateMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_code: components["parameters"]["ServerCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPServerRequest"];
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    deactivateMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_code: components["parameters"]["ServerCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    healthCheckMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_code: components["parameters"]["ServerCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listMCPTools: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_code: components["parameters"]["ServerCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                version: components["parameters"]["WorkflowVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    updateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                version: components["parameters"]["WorkflowVersion"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    activateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                version: components["parameters"]["WorkflowVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    deactivateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_code: components["parameters"]["AgentCode"];
                version: components["parameters"]["WorkflowVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["Envelope"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string;
                    /** Format: password */
                    password?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Envelope"];
        };
    };
}
